# Generated by Django 5.0.6 on 2024-06-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrazoRobotico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('modelo', models.TextField()),
                ('fechaAgregado', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'brazo robotico',
                'verbose_name_plural': 'brazos roboticos',
            },
        ),
    ]
