# Generated by Django 5.0.6 on 2024-06-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_brazorobotico_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brazorobotico',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
    ]
